module.exports={
    showAbout:(req,res)=>{
        res.render("about");
    },
    showContact:(req,res)=>{
        res.render("contact");
    },
    showIndex:(req,res)=>{
        res.render("index");
    }
};